# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				trapped_chest = true
				blast_furnace = true

			[light_sources.settings.block_entities.environmentz]
				laval_cauldron_block_entity = true

			[light_sources.settings.block_entities.ducts]
				duct = true

			[light_sources.settings.block_entities.gofish]
				astral_crate = true

			[light_sources.settings.block_entities.ae2]
				debug_energy_gen = true
				crafting_storage = true
				debug_phantom_node = true
				inscriber = true
				quantum_ring = true
				sky_compass = true
				paint = true
				interface = true
				creative_energy_cell = true
				cable_bus = true
				sky_chest = true
				crafting_unit = true
				wireless_access_point = true
				debug_item_gen = true
				light_detector = true
				quartz_growth_accelerator = true
				pattern_provider = true
				energy_acceptor = true
				condenser = true
				dense_energy_cell = true
				crafting_monitor = true
				vibration_chamber = true
				debug_chunk_loader = true
				spatial_pylon = true
				chest = true
				controller = true
				debug_cube_gen = true
				molecular_assembler = true
				cell_workbench = true
				spatial_io_port = true
				energy_cell = true
				charger = true
				spatial_anchor = true
				security_station = true
				drive = true
				io_port = true

			[light_sources.settings.block_entities.graveyard]
				urn_block_entity = true
				gravestone_block_entity = true

			[light_sources.settings.block_entities.blockus]
				wooden_barrel = true

			[light_sources.settings.block_entities.urns]
				clay_urn = true

			[light_sources.settings.block_entities.voidz]
				void_block_entity = true
				void_portal_entity = true

			[light_sources.settings.block_entities.betternether]
				furnace = true
				forge = true
				nether_brewing_stand = true
				chest_of_drawers = true

			[light_sources.settings.block_entities.cauldrons]
				suspicious_stew_cauldron = true

			[light_sources.settings.block_entities.bountiful]
				board-be = true

			[light_sources.settings.block_entities.agape_space]
				green_lamp = true
				conveyor = true
				airlock_base = true
				motor = true
				catalyzer = true
				powergen = true
				life_support = true
				cloning_device = true
				colony_command = true
				airlock_field = true
				storage = true
				miner_drill = true
				starship_control = true
				fan = true
				electro = true
				portal_beam_block = true
				power_furnace = true
				redstone_motor = true
				gearbox = true
				press = true
				rocket_station = true
				crusher = true
				space_crystal = true
				packer = true
				trigger_block = true
				red_lamp = true
				blue_lamp = true
				sulfur_vent = true
				oxy_gen = true
				fluid_pump = true
				fluid_tank = true
				auto_constructor = true
				wire = true
				solarcon = true
				luxury_game1 = true
				luxury_game2 = true
				battery_block = true
				starship_powersource = true
				powered_panel = true
				solargen = true

			[light_sources.settings.block_entities.adventurez]
				dragon_egg_entity = true
				stone_holder_entity = true
				piglin_flag_entity = true
				shadow_chest_entity = true

			[light_sources.settings.block_entities.dehydration]
				campfire_cauldron_entity = true

			[light_sources.settings.block_entities.waystones]
				waystone = true

			[light_sources.settings.block_entities.auto_planter]
				planter_tile = true
				planter_upgraded_tile = true

			[light_sources.settings.block_entities.betteranimalsplus]
				head = true
				trillium = true

			[light_sources.settings.block_entities.farmingforblockheads]
				market = true
				feeding_trough = true
				chicken_nest = true

			[light_sources.settings.block_entities.adorn]
				drawer = true
				kitchen_cupboard = true
				trading_station = true
				shelf = true

			[light_sources.settings.block_entities.bosses_of_mass_destruction]
				void_lily = true
				mob_ward = true
				void_blossom_block = true
				monolith_block = true
				levitation_block = true

			[light_sources.settings.block_entities.conjuring]
				gem_tinkerer = true
				blackstone_pedestal = true
				soulfire_forge = true
				conjurer = true
				soul_weaver = true
				soul_funnel = true

			[light_sources.settings.block_entities.dark-enchanting]
				dark_enchanter = true

			[light_sources.settings.block_entities.ancientgateways]
				gateway_block_entity = true

			[light_sources.settings.block_entities.bclib]
				barrel = true
				chest = true
				furnace = true
				sign = true

			[light_sources.settings.block_entities.earthtojavamobs]
				rainbow_bed = true

			[light_sources.settings.block_entities.arcanus]
				display_case = true
				fillable_bookshelf = true

			[light_sources.settings.block_entities.dml-refabricated]
				loot_fabricator = true
				trial_keystone = true
				matter_condenser = true

			[light_sources.settings.block_entities.gizmos]
				firework_star_block = true

			[light_sources.settings.block_entities.xps]
				entity_xp_obelisk = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				copper_golem = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.endgoblintraders]
				end_goblin_trader = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.megaparrot]
				megaparrot = true

			[light_sources.settings.entities.darkwaters]
				mohast = true
				miraid_hallucination = true
				craeken = true
				aberration = true
				manaraw = true
				sight_hunter = true
				miraid = true

			[light_sources.settings.entities.ae2]
				charged_quartz = true
				growing_crystal = true
				singularity = true
				tiny_tnt_primed = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				skeleton_creeper = true
				ghoul = true
				reaper = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				chair = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.adventurez]
				skeleton_vanguard = true
				deer = true
				thrown_rock = true
				desert_rhino = true
				small_stone_golem = true
				piglin_beast = true
				blaze_guardian = true
				ender_whale = true
				shaman = true
				dragon = true
				stone_golem = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				red_fungus = true
				void_cloud = true
				summoner = true
				void_bullet = true
				orc = true
				the_eye = true
				necromancer = true
				fire_breath = true
				void_fragment = true
				brown_fungus = true
				blaze_guardian_shield = true
				nightmare = true
				mammoth = true
				void_shade = true
				tiny_eye = true
				gilded_stone = true
				wither_puppet = true
				enderwarthog = true
				void_shadow = true
				amethyst_shard = true

			[light_sources.settings.entities.agape_space]
				hoverbike = true
				space_pirate_commander = true
				laserbeam_arrow = true
				europa_fish = true
				europa_fish_a = true
				titan_slime = true
				mmu = true
				space_cat = true
				space_mite = true
				rocket_ship_cargo = true
				space_pirate = true
				rocket_ship = true
				rocket_ship_v3 = true
				rocket_ship_v2 = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.boatcontainer]
				ender_chest_boat = true
				chest_boat = true

			[light_sources.settings.entities.snowpig]
				snow_pig = true

			[light_sources.settings.entities.companion_bats]
				dynamite = true
				bat = true

			[light_sources.settings.entities.vanilla_degus]
				degu = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				octopus = true
				goose = true
				badgerdirt = true
				songbird = true
				eel_freshwater = true
				squid_giant = true
				turkey_egg = true
				golden_goose_egg = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				pheasant_egg = true
				shark = true
				flying_fish = true
				piranha = true
				goose_egg = true
				bobbit_worm = true
				barracuda = true
				nautilus = true
				moose = true
				tarantula = true
				badger = true
				eel_saltwater = true
				squirrel = true
				brownbear = true
				walrus = true
				horseshoecrab = true
				turkey = true
				squid_colossal = true
				coyote = true
				tarantulahair = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.ottercraft]
				otter = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				blue_fireball = true
				spore_ball = true
				obsidilith = true
				petal_blade = true
				comet = true
				gauntlet = true
				soul_star = true
				void_blossom = true

			[light_sources.settings.entities.golemsgalore]
				obsidian_golem = true
				amethyst_golem = true
				laser_golem = true

			[light_sources.settings.entities.arachnids]
				flare = true
				brainbug = true
				warrior = true
				ton_block = true
				arkellian = true
				bugplasma = true
				tanker = true
				ton = true
				762 = true
				mz90_block = true
				mz90 = true
				hopper = true
				plasma = true
				worker = true
				scorpion = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				pollen_puff = true
				beehemoth = true

			[light_sources.settings.entities.conjuring]
				soul_feller = true
				soul_projectile = true
				soul_magnet = true
				soul_digger = true

			[light_sources.settings.entities.dragonloot]
				dragon_trident = true

			[light_sources.settings.entities.eeriehauntings]
				soulballprojectile = true

			[light_sources.settings.entities.mythicmounts]
				netherbat = true
				ridinglizard = true
				courierbird = true
				moth = true
				nudibranch = true
				direwolf = true
				dragon = true
				griffon = true
				nightmare = true
				geckotoalizard = true

			[light_sources.settings.entities.aoc]
				elvish_bat = true
				snow_cannon = true
				evil_elf = true
				evil_elf_brute = true
				raider_elf = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.aqupd]
				caracal = true
				grizzly_bear = true

			[light_sources.settings.entities.ancientgateways]
				chorus_ink_entity = true

			[light_sources.settings.entities.campchair]
				siting = true

			[light_sources.settings.entities.earthtojavamobs]
				pink_footed_pig = true
				cream_cow = true
				flecked_sheep = true
				midnight_chicken = true
				umbra_cow = true
				rainbow_sheep = true
				mottled_pig = true
				bold_striped_rabbit = true
				long_nosed_sheep = true
				amber_chicken = true
				bouldering_zombie = true
				furnace_golem = true
				vested_rabbit = true
				rotten_flesh_projectile = true
				bronzed_chicken = true
				jumbo_rabbit = true
				bone_shard = true
				moobloom = true
				stormy_chicken = true
				rocky_sheep = true
				jolly_llama = true
				fancy_chicken = true
				moolip = true
				glow_squid = true
				sunset_cow = true
				pale_pig = true
				melon_seed_projectile = true
				piebald_pig = true
				muddy_foot_rabbit = true
				dairy_cow = true
				spotted_pig = true
				skeleton_wolf = true
				gold_crested_chicken = true
				wooly_cow = true
				freckled_rabbit = true
				muddy_pig = true
				ashen_cow = true
				sooty_pig = true
				patched_sheep = true
				melon_golem = true
				harelequin_rabbit = true
				horned_sheep = true
				cookie_cow = true
				pinto_cow = true
				fuzzy_sheep = true
				cluckshroom = true
				bone_spider = true
				albino_cow = true
				viler_witch = true
				inky_sheep = true
				tropical_slime = true
				skewbald_chicken = true
				lobber_zombie = true

			[light_sources.settings.entities.arcanus]
				arcane_barrier = true
				magic_missile = true
				solar_strike = true

			[light_sources.settings.entities.oxidized]
				copper_golem = true

			[light_sources.settings.entities.dawn]
				custom_tnt = true
				flying_block = true

			[light_sources.settings.entities.dml-refabricated]
				system_glitch = true

			[light_sources.settings.entities.gizmos]
				tamed_ravager = true
				cultivated_shulker = true
				eye_of_ender_arrow = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.coldsnaphorde]
				frostycow = true
				pcoldsnapbrawler = true
				coldsnapgifter = true
				coldsnapbrawler = true
				ecoldsnapstabber = true
				lightningsnowballprojectile = true
				coldsnapzapper = true
				ncoldsnapgunner = true
				pcoldsnapgunner = true
				ncoldsnapstabber = true
				pcoldsnapstabber = true
				coldsnapstabber = true
				snowiersnowballprojectile = true
				ecoldsnapbrawler = true
				gunnerprojectile = true
				thrownchorusprojectile = true
				ncoldsnapzapper = true
				ncoldsnapbrawler = true
				ecoldsnapsnowballer = true
				ecoldsnapgunner = true
				ncoldsnapgifter = true
				ecoldsnapgifter = true
				ncoldsnapsnowballer = true
				rocksnowballprojectile = true
				coldsnapsnowballer = true
				pcoldsnapsnowballer = true
				pcoldsnapzapper = true
				coldsnapgunner = true
				pcoldsnapgifter = true
				ecoldsnapzapper = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				moobloom = true

